apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config
  namespace: emqx
data:
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "ip"
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  EMQX_LISTENER__SSL__EXTERNAL: "8883"
  EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: "/home/emqx/api-tls.key" 
  EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: "/home/emqx/api-tls.crt"
  EMQX_LISTENER__WSS__EXTERNAL: "8084"
  EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: "/home/emqx/api-tls.key" 
  EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: "/home/emqx/api-tls.crt"