apiVersion: v1
kind: Service
metadata:
  name: emqx-nodeport
  namespace: emqx
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 30482
    protocol: TCP
    targetPort: 1883
  - name: mqttssl
    port: 32513
    protocol: TCP
    targetPort: 8883
  - name: mgmt
    port: 31630
    protocol: TCP
    targetPort: 8081
  - name: websocket
    port: 30848
    protocol: TCP
    targetPort: 8083
  - name: wss
    port: 32729
    protocol: TCP
    targetPort: 8084
  - name: dashboard
    port: 31513
    protocol: TCP
    targetPort: 18083
