kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-pvc
  namespace: emqx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
