apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: emqx
  name: emqx
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: emqx
  name: emqx
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: emqx
  name: emqx
subjects:
  - kind: ServiceAccount
    name: emqx
    namespace: emqx
roleRef:
  kind: Role
  name: emqx
  apiGroup: rbac.authorization.k8s.io